
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjkwIiwibmJmIjoxNzExNDYwMDMxLCJleHAiOjE3MTE0NjU0MzEsImlhdCI6MTcxMTQ2MDAzMSwiaXNzIjoiQXBpQ2FiZWxlaXJlaXJvVjIiLCJhdWQiOiJNaW5oYUFwaSJ9.pbYhKcBbGYZR_vFbu0A_V798F3b92mQMNuJPAfO0Tgs";

export default token;