
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjgwIiwibmJmIjoxNzExMzI5OTc3LCJleHAiOjE3MTEzMzcxNzcsImlhdCI6MTcxMTMyOTk3NywiaXNzIjoiQXBpQ2FiZWxlaXJlaXJvVjIiLCJhdWQiOiJNaW5oYUFwaSJ9.n53tTzbYO46uVPsuFTrwtJaFE3_waBrLuqJzSCl_yKM";

export default token;