
const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjgwIiwibmJmIjoxNzExMzYzMTU5LCJleHAiOjE3MTEzNzAzNTksImlhdCI6MTcxMTM2MzE1OSwiaXNzIjoiQXBpQ2FiZWxlaXJlaXJvVjIiLCJhdWQiOiJNaW5oYUFwaSJ9.IYy-Ga5uE0H5HWafBh1bAiZotLAcFo6Oiq-tFmde5JY";

export default token;